### ISSUE TITLE
CORS error?

### ISSUE THREAD

**Issue by gitonthescene** [dzaima/intrinsics-viewer#2]
I haven't put much energy into tracking this down, but I figured I'd at least report getting this error.

<img width="712" alt="Screenshot 2024-11-11 at 12 49 27" src="https://github.com/user-attachments/assets/266dedac-f726-4352-93a7-81793ef0dc0d">

**Comment by dzaima** [comment]
You might need to host it with `python3 -m http.server` or similar, or mess with some browser settings to disable strict CORS for `file://`; unfortunately by default browsers limit what relative files `file://` can access, and CORS cannot be controlled without a webserver.

**Comment by gitonthescene** [comment]
Starting an explicit server did work.  Thanks.
